# Generated by Django 6.0.4 on 2026-04-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='original_url',
            field=models.URLField(help_text='The long URL to shorten', unique=True),
        ),
    ]
