# Generated by Django 5.2.8 on 2025-12-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_shorturl_user_alter_shorturl_original_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(max_length=2048, unique=True, verbose_name='Original Long URL')),
                ('short_code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Short Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'URL Mapping',
                'verbose_name_plural': 'URL Mappings',
            },
        ),
    ]
